### PR TITLE
Fix IPv6 detection. Fixes #24

### LINKED ISSUE #24: PP.pm not recognising IPv6 addresses?
I'm puzzled by line 76 of lib/MAxMind/DB/Reader/PP/pm:

    my $is_ipv6_addr  = $addr =~ /::/;

This seems to cause IPv6 addresses not containing :: to be treated as IPv4 addresses, with obvious consequences. There are lots of valid IPv6 addresses that don't contain '::', surely that should be ':'?

Installing the XS version of the reader has worked around the problem for me, but recorded here in case it's useful.

Jon.

### PR DESCRIPTION
**Pull request by oschwald**

### CODE REVIEW

File: lib/MaxMind/DB/Reader/Role/Reader.pm [hunk 1]
```diff
@@ -36,6 +36,9 @@ sub record_for_address {
     die 'You must provide an IP address to look up'
         unless defined $addr && length $addr;
 
+    # We validate the IP address here as libmaxminddb allow more the liberal
```
Comment (autarch) [inline lib/MaxMind/DB/Reader/Role/Reader.pm]: Typo in comment - `s/allow/allows/`
